### ISSUE TITLE
[FEATURE REQUEST] Quick Reblog

### ISSUE THREAD

**Issue by BeeFox-sys** [MasterSteelblade/WaterfallBugsFeatures#1]
**Motivation and Context**
This feature would encourage people to reblog more as it would require less steps to reblog a post
this would also allow people who have issues like executive dysfunction or too low energy for the extra steps to reblog more easily

**Is your feature request related to a problem? Please describe.**
I always find it difficult to reblog posts as it takes several steps to do so, and my brain just doesn't like that, I want to reblog more while still allowing my brain to be happy

**Describe the feature/solution you'd like**
A simple button would do nicely! potentially with an option to add tags directly on the same page, or even better post with a default set of tags (defined per post type maybe?)

**Describe alternatives you've considered**
Browser plugins could be used but that makes it inaccessable to mobile users and certain browsers

**Is there a way to do this already?**
Not currently

**Additional context**
even if this feature is not included, "auto tags" or default tags would be greatly appreciated from those of us who have trouble with this sort of thing, and would make one less step to do

**Comment by MasterSteelblade** [comment]
This is implemented and working on the dev build, so closing this now for tracking purposes.
