### ISSUE TITLE
[FEATURE REQUEST] Change submit button placement on settings pages

### ISSUE THREAD

**Issue by Vyling** [MasterSteelblade/WaterfallBugsFeatures#17]
**Motivation and Context**
personal motivation: Whenever I change something minor at the top, I will have to scroll all the way down - but also not ALL the way down, but just enough to get to the button. The placement is kinda unintuitive.
Others have mentioned too that the button didn't seem to appear to belong to the whole page. 
Having studied UX, the main issue I see is that it is too close to the last field. The closer a button is to a field, the more the user thinks that the button belongs to only that field.

**Is your feature request related to a problem? Please describe.**
The problem is that the button is not intuitive right now. Its purpose is mistaken, and small changes feel bothersome.

**Describe the feature/solution you'd like**
I tried to think of a good solution, but honestly there's only one that I could see working. I know most web-devs hate that, but having it scroll with the page would be a huge help I think. The best way to not have it look ugly, would be to add it to the header and have the header scroll with the page. That way, the submit button is always in reach and it's clear that it's meant for this page.

**Describe alternatives you've considered**
One alternative I've considered is to have a line below the form which it submits. But that might be confusing again, because it can tell users that the button is for the next form.
Another alternative I was thinking about is to have the button directly somewhere at the top right. But then user might end up confused when they've scrolled down and missed the button earlier.
Another solution I came up with is to have each category split into their own tabs, and have a submit button for each category. But that's a lot more work I think.

**Is there a way to do this already?**
The user can try out and learn. But I'm more a friend of a site being intuitive instead of the user having to learn.

**Additional context**
N/A

**Comment by leporid5873** [comment]
I think it'd work best with the safe button at the top of the page, above all settings.
You see it when you open settings and even on mobile you give one fast scroll and you're back up.
![Screenshot_20210125-221445_Firefox](https://user-images.githubusercontent.com/77962916/105767072-e181af00-5f5a-11eb-8b5f-0df8e199a218.jpg)

**Comment by zagoon** [comment]
Agreed that the submit button needs to be moved elsewhere for clarity. My first reaction to trying to change my blog settings was to assume that it must automatically save, and after that assumption was repeatedly proven false I really had to comb the page to figure out which button would store my changes.

I think the most confusing aspect right now is that "Submit" is immediately under the post queue but above two other sections, which made me instinctively read it as a button specifically for saving queue preferences and nothing else.

**Comment by MasterSteelblade** [comment]
Partially resolved by the colour and wording change, but there's not really anywhere better to put it right now.
