### ISSUE TITLE
[FEATURE REQUEST] quick reblog confirmation msg

### ISSUE THREAD

**Issue by star-rice** [MasterSteelblade/WaterfallBugsFeatures#18]
very small thing, but would be good if when you quick reblog something a little tool tip pops after you press "Reblog" informing you that it was successful, perhaps also indicating where it was reblogged to. IE - "Post successfully reblogged to Star-Rice!" It help the site feel responsive and makes brain feel safe.

**Comment by MasterSteelblade** [comment]
This should already be the case - does the reblog icon not turn green afterwards? It _should_ be doing so without needing to reload
