### ISSUE TITLE
[BUG] Art icon on posts displaced

### ISSUE THREAD

**Issue by Vyling** [MasterSteelblade/WaterfallBugsFeatures#20]
**Describe the bug**
The art icon displayed on the top right corner of each art post is not centered vertically, but seems to stick to the top.

**To Reproduce**

1. Go to Dashboard
2. Look for an art post
3. Look at the top right corner of the art post
4. Be devastated

**Expected behavior**
The icon should be vertically centered in the post header

**Screenshots**
![image](https://user-images.githubusercontent.com/30179258/105642729-b3816980-5e8b-11eb-8444-0c3e6c897449.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 3.5.2115.87 (64-Bit)
maybe it also helps to mention, that the width of my browser is about ~1000px

**Additional context**
N/A

**Comment by MasterSteelblade** [comment]
Fixed! I don't think they were vertically centred before but they were certainly right in the corner, so that's what I've gone back to.
