### ISSUE TITLE
[BUG] Post not found when following links in notes of preupdate posts

### ISSUE THREAD

**Issue by vincebirds** [MasterSteelblade/WaterfallBugsFeatures#21]
**Describe the bug**
On certain posts, (apparently only ones from before the WF 2.0 update, from what I can tell,) the "(user) reblogged a (post)" post link to the specific instance of the post that was reblogged leads to a "Post not found" message instead of the post in question. The url to the post seems fine, but the post itself is missing. The links work fine when concerning posts posted AFTER the update, though?

**To Reproduce**
1. Access the notes of a post originating before the WF 2.0 update.
2. Click on the (post) portion of any(?) "(user) reblogged a (post)" note.
4. See error.
This process also works on "(user) reblogged (post)" notifications on the dashboard. 

**Expected behavior**
(post) link is expected to take me to the version of the post that (user) reblogged. Or, I guess if that's been changed, it should take me to the version of the post on their blog?

**Screenshots**
I don't think screenshots are applicable to this situation? This is a reblog of [this post](https://vincebirds.waterfall.social/post/455166)
![image](https://user-images.githubusercontent.com/77938319/105642602-9030cd00-5e3f-11eb-8aca-30ad153e988b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave V1.19.86 (Chromium browser)

**Additional context**
Don't know if any additional context is required here? I am so nervous though :(. Also I'm not sure how this is impacted by posts made *before* the update where a reblog happened *after* the update

**Comment by MasterSteelblade** [comment]
Unfortunately this is a limitation of the data that was kept pre-update - it didn't keep links to the post that was created after the fact, so this can't be fixed.
