### ISSUE TITLE
[BUG] Featured art post disappears after viewing in fullsize

### ISSUE THREAD

**Issue by Vyling** [MasterSteelblade/WaterfallBugsFeatures#23]
**Describe the bug**
When you click on a featured art post at the sidebar to view it in fullsize, the original image on the sidebar is missing. Going back to the dash does not bring it back, but after a reload of the page it's back.

**To Reproduce**
1. Go to Dashboard
2. Click on featured art post image to look at its glorious fullsize
3. Look at the sidebar behind the image, where the image once was
4. Click back onto the site to return to the Dashboard
4. Look at the exact same place again and curse the thieves

**Expected behavior**
The image should still be visible in the sidebar after viewing it in fullsize.

**Screenshots**
![image](https://user-images.githubusercontent.com/30179258/105643227-d95c3d80-5e8e-11eb-883c-afded497f176.png)
![image](https://user-images.githubusercontent.com/30179258/105643242-e9741d00-5e8e-11eb-8117-64688a14a94a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 3.5.2115.87 (64-Bit)

**Additional context**
[insert a funny comment here]

**Comment by MasterSteelblade** [comment]
Art Theft 3.0: Now you can steal it

Confirmed bug, albeit a hilarious one.

**Comment by MasterSteelblade** [comment]
And now a fixed bug.
