### ISSUE TITLE
[BUG] Outdated Browser Warning in FireFox iOS

### ISSUE THREAD

**Issue by KingHelios33** [MasterSteelblade/WaterfallBugsFeatures#24]
**Describe the bug**
After the site came back up, I logged in to the site on my iPad in FireFox. All images are missing and either won’t appear or are replaced with squares with nothing in them. It also happened on my iPhone as well, both using FireFox to browse. I even tried to use Google Chrome to see if it was a browser issue, but Chrome does the same thing.

**To Reproduce**
1. Go to Waterfall main page.
2. Click on Login.
3. Enter email and password.
4. Once it redirects to my dashboard, no images.

**Expected behavior**
I was expecting for all images to show, but I’m unsure why this happened.

**Screenshots**

https://ibb.co/P1zkF0b

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 14.3
 - Browser: FireFox
 - Version: 29

**Comment by MasterSteelblade** [comment]
This'll be an ongoing process, as per the last staff post - I'll leave this open for now until it's finished, so that anyone else checking here can see it.

**Comment by MasterSteelblade** [comment]
For those checking in to see if this is here - conversions are now in progress! It'll be a couple days again before everything is done, but you should be seeing some stuff at least.

**Comment by MasterSteelblade** [comment]
A patch will be deployed in a few hours that solves this, once the conversion process finishes. Closing as fixed!
