### ISSUE TITLE
[BUG] Invite table not readable on dark moss

### ISSUE THREAD

**Issue by Vyling** [MasterSteelblade/WaterfallBugsFeatures#25]
**Describe the bug**
The table to display all invites in the blog settings is not readable. The font color is as dark as the background color. Strg+F5 did not fix it.

**To Reproduce**
1. Turn on Dark Moss Theme (press Strg+F5/delete Cache)
2. Go to Blog Settings
2. Scroll down to Invites
3. Look at the table list with the invites

**Expected behavior**
The font should be a lighter color, matching the other text on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/30179258/105643988-8042d880-5e93-11eb-9d6e-3289a9413123.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 3.5.2115.87 (64-Bit)

**Additional context**
N/A

**Comment by MasterSteelblade** [comment]
Fixed! May require a Ctrl-F5 refresh to reload the theme.
