### ISSUE TITLE
[BUG] Cannot look up tag for singular blog

### ISSUE THREAD

**Issue by star-rice** [MasterSteelblade/WaterfallBugsFeatures#26]
**Describe the bug**
When clicking through tags on any given blog to see more posts in the same tag of that user, instead of pulling https://blogname.waterfall.social/tagged/tagname it pulls https://waterfall.social/search/tagname which displays all posts in a given tag for all users on the site and not just the one. When trying to go to https://blogname.waterfall.social/tagged/tagname manually it fails with the following error

**To Reproduce**
1. Go to a blog
2. Click on a tag on any given post (for example #art)
3. Scroll down to literally anywhere

**Expected behavior**
At present there's no way, afaik, to see a tag for just your blogs posts like we used to be able to do.

**Screenshots**

![image](https://user-images.githubusercontent.com/75922700/105644122-77351580-5e59-11eb-8977-34f9c37892c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 84.0.2 (64-bit)

**Comment by MasterSteelblade** [comment]
Fixed!
