### ISSUE TITLE
[BUG] Cannot delete blogs

### ISSUE THREAD

**Issue by star-rice** [MasterSteelblade/WaterfallBugsFeatures#29]
**Describe the bug**
If you have a blog, you get an error when trying to delete it. Curiously, all posts made for said blog get deleted, but the blog remains. 

Also curiously, if one of those deleted posts was liked and the user who liked it goes into their Likes, the deleted post is still visible (though, of course the permalink doesn't work)

**Screenshots**
Error: There was an error trying to delete the blog. Please contact support. 
![image](https://user-images.githubusercontent.com/75922700/105644885-ca10cc00-5e5d-11eb-9acf-f011cc6542b5.png)

Screenshot from another blogs liked page:
![image](https://user-images.githubusercontent.com/75922700/105644946-2e339000-5e5e-11eb-9e4f-1687c6c54e6d.png)
Permalink for post in question: https://starstestblog.waterfall.social/post/463128

**Comment by MasterSteelblade** [comment]
Fixed!
