### ISSUE TITLE
[BUG] Footer broken in page editing interface

### ISSUE THREAD

**Issue by greysdawn** [MasterSteelblade/WaterfallBugsFeatures#30]
**Describe the bug**
The site footer appears behind the text editor in the page editing interface. Comically enough, you can control the position of the footer using new lines in the text editor.

**To Reproduce**
1. Go to blog settings
2. Create a new page, or edit an existing (short) one
3. Observe the footer peeking behind the text editor
4. Enter new lines in; observe the footer changing position

**Expected behavior**
The footer should be placed in its proper location beneath the text editor.

**Screenshots**
![A gif of the behavior](https://user-images.githubusercontent.com/29555267/105645177-edd90f80-5e67-11eb-9263-aa84ed691733.gif)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 8
 - OS: Android 9
 - Browser: Chrome
 - Version: 88.0.4324.93 (latest)

**Comment by MasterSteelblade** [comment]
Ultimate mad hax solved it by removing it from the pages. Thanks for the heads up!
