### ISSUE TITLE
[BUG] Cannot edit images

### ISSUE THREAD

**Issue by ICantChooseNames** [MasterSteelblade/WaterfallBugsFeatures#32]
**Describe the bug**
Editing an image or art post does not allow you to delete, reorder, or reupload images to said post.

**To Reproduce**
1. Find an image or art post you wish to edit (or post one)
2. Click to edit the image/art post
3. Notice a distinct lack of image

**Expected behavior**
The image to appear above the text box so that it may be deleted, moved, or re-added

**Screenshots**
![noedit](https://user-images.githubusercontent.com/77937232/105645680-3a711a80-5e69-11eb-901c-07874fb256e4.png)

**Desktop (please complete the following information):**
 - OS: OpenSUSE Leap 15.2
 - Browser: Firefox
 - Version 28.6.1esr (64-bit)

**Additional context**
I just wanted to upload a higher quality image for my one art post ;u;

**Comment by MasterSteelblade** [comment]
Fixed! (I think)
