### ISSUE TITLE
[BUG] Some settings lie to you

### ISSUE THREAD

**Issue by ICantChooseNames** [MasterSteelblade/WaterfallBugsFeatures#33]
**Describe the bug**
Minor bug(s)?- Some settings seem to 'stick' with a specific option even if that's not the actual setting used. There's two in particular I've noticed thus far so I'll group them together, though they don't act the exact same.

1) Image ID toggle appearing "off", but always seems to be on (???)
2) Supposed blog theme not lining up with current blog theme between blogs, but rather whatever you last selected regardless of blog (Does not affect blog theme on other blogs)

**To Reproduce**
_Image ID toggle:_
1. Go to user settings, enable Image ID toggle
2. Go to blog settings
3. Return to user settings, the ID toggle now appears to be off
4. Find an image with Image ID- the ID is there regardless of toggle

_Blog theme misnaming:_
1. Set a theme on one blog
2. Switch to a blog that uses a different theme
3. Look at the 'selected' blog theme

**Expected behavior**
For Image ID toggle to appear on if set to on, and Image IDs to not appear if it is set to off.
For the supposed blog theme to line up with the theme the blog uses.

**Desktop (please complete the following information):**
- OS: OpenSUSE Leap 15.2
- Browser: Firefox
- Version 28.6.1esr (64-bit)

**Comment by MasterSteelblade** [comment]
Possible fix pushed - can you confirm it works now?

**Comment by ICantChooseNames** [comment]
Blog theme still lies to you, unfortunately :\

**Comment by greysdawn** [comment]
"show in nav" option also lies to you when working on pages (resets after updating the page)- might be why they aren't showing up on blogs? at least on mobile they're invisible

**Comment by MasterSteelblade** [comment]
These _should_ be fixed now - pages don't show on mobile currently, that's a separate bug I'll make an issue for.

**Comment by ICantChooseNames** [comment]
Blog theme names still stick, but I discovered that cache has something to do with it- clearing cache while on a blog with the bug active will make the blog settings page display the correctly applied theme, but it will happen again when you switch to a blog with a different theme

**Comment by MasterSteelblade** [comment]
Hm, alright - pushed another small patch, maybe that'll work. Let me know!

**Comment by ICantChooseNames** [comment]
Yes, that worked- thank you!
