### ISSUE TITLE
[BUG] Pinned posts aren't being pinned

### ISSUE THREAD

**Issue by Lynaiss** [MasterSteelblade/WaterfallBugsFeatures#34]
**Describe the bug**
The toggle for the pinned posts resets back to off even when saving it set to "on". As a result posts do not get pinned.

**To Reproduce**
1. Edit your post and set the "pin this post" toggle on.
2. Hit "Save".
3. Open your blog - the post is not pinned.
4. Hit "Edit" on the post - the toggle is off again.

**Expected behavior**
The pinned posts toggle doesn't work and posts aren't getting pinned to the top of your blog.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 84.0.2 (64-bit)

**Additional context**
This occurs both on posts before and after the rewrite.

**Comment by MasterSteelblade** [comment]
Fixed!
