### ISSUE TITLE
[BUG] Badges not removable on mobile (Android/Chrome)

### ISSUE THREAD

**Issue by anarchyrain** [MasterSteelblade/WaterfallBugsFeatures#35]
**Describe the bug**
You cannot click/tap to remove badges on mobile (specifically the latest version of Chrome on Android) - the badge sometimes grows slightly larger upon clicking, if it responds at all.

**To Reproduce**
1. In settings, choose a badge.
2. Try to remove it by tapping on it.
3. It does not work.

**Expected behavior**
I expected the badge to be removed.

**Smartphone (please complete the following information):**
 - Device: LG G7 Fit
 - OS: Android... something.
 - Browser: Chrome
 - Version: Latest available in Play Store.

**Comment by MasterSteelblade** [comment]
Unfortunately this seems to be a limitation of mobile - I've tried all three permutations of touch/click events that I know of and none of them work, so I can't really do anything here eithout compromising the desktop experience. The best bet is to wait for the app for this, sorry.
