### ISSUE TITLE
[BUG] Dashboard Dark Moss theme makes text light

### ISSUE THREAD

**Issue by MarrowInTheBone** [MasterSteelblade/WaterfallBugsFeatures#36]
**Describe the bug**
When trying to type while making a post with the dashboard theme set as Dark Moss, the text is a very light green, making it hard to see. Other text is also made light, like that in settings, and the "boxes" in settings are also light.

**To Reproduce**
1. Go to 'User Settings'
2. Scroll down to 'Dashboard Theme'
3. Choose 'Dark Moss' as dashboard theme
4. Click submit
5. Make a text post or go back to 'User Settings'
6. See error

**Expected behavior**
The text should instead be black. The "boxes" in the settings should also be darker.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/77948273/105656490-f6414280-5e87-11eb-9922-abbbe3d899ab.PNG)
![Capture1](https://user-images.githubusercontent.com/77948273/105656516-0b1dd600-5e88-11eb-9ef4-f261d31207ec.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 84.0.2 (64-bit)

**Additional context**
I was not able to reproduce the issue on my Android smartphone. I tested using both DuckDuckGo and Firefox mobile browsers on their most current version.

**Comment by MasterSteelblade** [comment]
Seems like you have an old version of the theme stuff loaded - can you try Ctrl-F5 to force refresh it?

**Comment by MarrowInTheBone** [comment]
That fixed the issue! Thanks!
