### ISSUE TITLE
[BUG] search/tag pages only returns dnr/dni posts

### ISSUE THREAD

**Issue by autiestella** [MasterSteelblade/WaterfallBugsFeatures#38]
**Describe the bug**
regardless of where searching, posts which CAN be reblogged will not appear - only those which can't 
posts still exist & can be viewed by other means (dashboard, main blog homepage, direct link, etc)
happens regardless of if from pre- or post-update, & regardless of post type
(discovery & dashboard seem to working as intend)

**To Reproduce**
1. enter any tag in main search, OR, enter any blog's /tagged/(tag) page
2. notice only dnr/dni posts show, be sad at lack rebloggable content - some entire pages just empty, esp if direct on blog

**Expected behavior**
in main site search: any post available for reblog show up; dnr/dni posts will not appear atall
on blog /tagged/(tag) page: all posts using tag to show (regardless of if dnr/dni, for sake of being able look back + organise, at least on your own blog) 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux mint
 - Browser firefox
 - Version 84.0.2

**Additional context**

**Comment by MasterSteelblade** [comment]
Fixed!

**Comment by autiestella** [comment]
unfort it's looking now like can't see any of dni/dnr posts even on own blog tag pages :( is there any possibility override this, when looking at your own blog? many of posts which personaly look back at (dream journal, linguistic refrence) are tagged dnr
