### ISSUE TITLE
[BUG] Wrong cursor over (un)follow

### ISSUE THREAD

**Issue by Vyling** [MasterSteelblade/WaterfallBugsFeatures#40]
**Describe the bug**
Very minor bug.
When I followed someone, I noticed that the cursor did not change to the hand, but turned into the cursor to mark text instead. _Functionality is not affected._

**To Reproduce**
1. Go to someone else's blog
2. Hover mouse over "Follow/Unfollow"

**Expected behavior**
The mouse cursor should behave like on any link.

**Screenshots**
Can't make a screenshot with the cursor, sorry. ;_;

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 3.5.2115.87 (64-Bit)
 - Browser window so small, the expandable menu appears

**Additional context**
N/A

**Comment by ICantChooseNames** [comment]
I've seen this in other areas, too- I'll provide a screenshot of those (as well as the [un]follow button as you mentioned)
![image](https://user-images.githubusercontent.com/77937232/105718711-88306600-5eef-11eb-8a00-cf59eaf947fe.png)

Admittedly I'm not sure where we're expected to click for the badges, hovering over the badge itself or the grey areas has just the pointer cursor but hovering over the text results in the text cursor- even if the entire area seems to be the button to apply it
...Also while taking this screenshot I noticed that the pride badge text is completely unreadable, at least in Dark Moss...

**Comment by Vyling** [comment]
I'm pretty sure the unreadable text was caused by this fix: #25 
Because both tables have the same text color.

**Comment by MasterSteelblade** [comment]
Fixed! May need a Ctrl-F5.
