### ISSUE TITLE
[BUG] Cannot respond to private asks/messages

### ISSUE THREAD

**Issue by BeeFox-sys** [MasterSteelblade/WaterfallBugsFeatures#41]
**Describe the bug**
You cannot post asks that are sent as private asks, even with a private response

**To Reproduce**
1. Receive a privately responded ask
2. Edit button does not appear 

**Expected behavior**
To be able to post the ask, or at the very least respond privately

**Screenshots**
(First ask is a private response to the second ask)
![image](https://user-images.githubusercontent.com/42090331/105692535-a24f6000-5f52-11eb-9383-48e0798fb8f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 84.0.2

**Smartphone (please complete the following information):**
 - Device: Remdi s3
 - OS: Android lolipop
 - Browser Chrome
 - Version Unknown (Latest)

**Additional context**
If this was intend, it has caused a negative effect, as many people use chains of private responses to ask to act as messages

**Comment by MasterSteelblade** [comment]
This is intended behaviour, as asks are largely intended for public posting - the private reply feature is for when an individual answer should be private, and they're not really intended to hold conversations through.

**Comment by BeeFox-sys** [comment]
while I understand why it is intended, at the moment this is the only way to communicate one on one onsite, and until a messaging function is added, this would be a great compromise.
as well as this, as the link "ask" as been replaced with "message" it is now confusing, if it is not intended for messaging a user
