### ISSUE TITLE
[BUG] Follow/Unfollow button acessability

### ISSUE THREAD

**Issue by BeeFox-sys** [MasterSteelblade/WaterfallBugsFeatures#42]
**Describe the bug**
the follow/unfollow button does not get selected when navigating by keyboard controls

**To Reproduce**
1. Go to any blog (except your own)
2. Navigate to the button via keyboard controls (skips over it)

**Expected behavior**
Tab controls can access the button

**Desktop (please complete the following information):**
    OS: Windows 10
    Browser Firefox
    Version 84.0.2

**Additional context**
The issue stems from the use of <span> for the button rather then something like <a>, this can be fixed using the "tabindex" attribute, setting it to 0 will allow for it to be ordered by the dom flow

**Comment by BeeFox-sys** [comment]
A few more places where this is an issue:
blog selection from the dropdown blog menu
switch blog in user settings
like button on post

and similar issues:
post creation bar (each post type gets selected twice)
quick reblog cannot be accessed via focusing reblog
featured post tab order is off, coming at the end of the list when visually it should be after the post types
post editor traps your keyboard navigation, you cannot tab to the next field
pride badges button in user settings is the first selected when using keyboard controls, instead of flowing with the page (not sure why this is, as the tab flow is correct, it must be getting focused by js when the page loads or something)
on the message creation page, the footer info is focused first, but is also invisible so you cannot see what is being selected

**Comment by MasterSteelblade** [comment]
Transferred these notes to the dev repository and will be implemented in the UI overhaul - closing for now to make things neater.
