### ISSUE TITLE
Titles cannot be changed on mobile

### ISSUE THREAD

**Issue by el-o-l** [MasterSteelblade/WaterfallBugsFeatures#43]
**Describe the bug**
In both drafts and published posts, the title is not available to edit nor remove.

**To Reproduce**
1. Go to a post or draft containing a title.
2. Click on 'edit'
3. Scroll down to the text box where editing occurs

**Expected behavior**
Expected to see the title as part of the text box where the post is edited, but it is only shown at the top where the original post (pre-edit) is displayed. 

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Lite
 - OS: Android 9
 - Browser: Firefox Nightly
 - Version: Latest

**Comment by MasterSteelblade** [comment]
It was actually editing titles in posts in general that wasn't there, but a patch will be deployed in a few hours that solves this, once the conversion process finishes. Closing as fixed!
