### ISSUE TITLE
[BUG] Queue tag missing

### ISSUE THREAD

**Issue by Vyling** [MasterSteelblade/WaterfallBugsFeatures#44]
**Describe the bug**
I have specified the tag "queue~" in the blog settings for my queue posts. But it won't appear on the posts that I queue.

**To Reproduce**
1. Go to blog settings and set a queue tag
2. Queue a post
3. Check queued posts

**Expected behavior**
I would expect each queued post to have the tag that I configured. In my case, "queue~"

**Screenshots**
![image](https://user-images.githubusercontent.com/30179258/105699183-3f84a700-5f07-11eb-83d9-e2ee6a733899.png)
I can't think of any other screenshot that would make sense-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Version 3.5.2115.87 (64-Bit)

**Additional context**
I hadn't changed the queue settings since the rewrite. They are still the same.

**Comment by MasterSteelblade** [comment]
This should be fixed now!
