### ISSUE TITLE
[BUG] Broken TOS and Guidelines links in page footer

### ISSUE THREAD

**Issue by ItsSidh** [MasterSteelblade/WaterfallBugsFeatures#45]
**Describe the bug**
The Terms of Service and Community Guidelines links in the page footer are broken. Terms leading to a completely blank page and Guidelines giving a 404

**To Reproduce**
1. Go to page footer
2. Click on either Terms of Service or Community guidelines links
3. See errors

**Expected behavior**
User would be navigated to the TOS and/or Guidelines pages respectively

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Firefox
 - Versions 87.0, and 84.0 respectively

**Comment by MasterSteelblade** [comment]
Fixed!
