### ISSUE TITLE
[BUG] Badges table not readable in Dark Moss

### ISSUE THREAD

**Issue by Vyling** [MasterSteelblade/WaterfallBugsFeatures#46]
**Describe the bug**

> ...Also while taking this screenshot I noticed that the pride badge text is completely unreadable, at least in Dark Moss...

_Originally posted by @ICantChooseNames in https://github.com/MasterSteelblade/WaterfallBugsFeatures/issues/40#issuecomment-766855257_

I guess thell missed that in the comment, so I'm gonna create a new issue instead!

**To Reproduce**
1. Go to Blog Settings
2. Scroll down to Badges
3. Expand Pride Flags
4. Look at table

**Expected behavior**
Either the table should be with a dark background or the text dark. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30179258/105741026-221d0080-5f3a-11eb-9bf6-5217dc6f78d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Version latest

**Additional context**
Probably caused by the fix for #25

**Comment by MasterSteelblade** [comment]
This should have been fixed already - does a Ctrl-F5 not fix it?

**Comment by Vyling** [comment]
No it doesn't, which is why I opened that. :< Sorry I should have mentioned that.

**Comment by MasterSteelblade** [comment]
All good, think I got it now - can you confirm?

**Comment by Vyling** [comment]
The table body is fine now, but the header is still bright

**Comment by MasterSteelblade** [comment]
Fixed! Sorry about that, I'm a dumbass.
