### ISSUE TITLE
[BUG] Blog names not visible when switching blogs in Light Theme 

### ISSUE THREAD

**Issue by peanutbuttercookiess** [MasterSteelblade/WaterfallBugsFeatures#48]
**Describe the bug**
In the menu to switch blogs, the font color used is white, making the blog names unreadable.

**To Reproduce**
1. Turn on Light Theme
2. Click on the dropdown menu to switch blogs
3. See the white blog names

**Expected behavior**
Blog names should be a darker color

**Screenshots**
![image](https://user-images.githubusercontent.com/16735794/105770901-cd738880-5f2d-11eb-9354-438dab2eca7d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.141

**Additional context**
Ctrl-F5 does not fix the issue

**Comment by MasterSteelblade** [comment]
A patch will be deployed in a few hours that solves this, once the conversion process finishes. Closing as fixed!
