### ISSUE TITLE
[BUG] broken post editor

### ISSUE THREAD

**Issue by autiestella** [MasterSteelblade/WaterfallBugsFeatures#49]
**Describe the bug**
post editor is broken, or, "beaned" as it were

**To Reproduce**
1. attempt to edit post (tested on text post, both w/ & w/o image embed)
2. see abomination

**Expected behavior**
to not be beaned

**Screenshots**
w/ image embed:
![Screenshot from 2021-01-25 17-21-30](https://user-images.githubusercontent.com/77951485/105774408-36a9ca80-5f33-11eb-926f-f2252d517fa5.png)
w/o:
![Screenshot from 2021-01-25 17-27-07](https://user-images.githubusercontent.com/77951485/105774423-3c9fab80-5f33-11eb-843d-68affa5b3894.png)

**devices**
computer running firefox 84.0.2 on linux mint
ipad running duckduckgo browser 7.61.8 on ios 12.5
(both were affected, so both included) 

**Additional context**
this only began sometime today; worked correctly last night

**Comment by MasterSteelblade** [comment]
I haven't been able to replicate this, does it still do it? Are there any specific circumstances leading up to it?

**Comment by autiestella** [comment]
ah!! perfect timing cause was just trying figure out what do abt this post - no, this not issue anymore, it just happened for short period of time on both device :o whatever it was seems to be resolve now, & not sure anyone else ran into it, so!!
