### ISSUE TITLE
[BUG?] delete button on outbox messages

### ISSUE THREAD

**Issue by autiestella** [MasterSteelblade/WaterfallBugsFeatures#50]
**Describe the bug**
assuming unless otherwise stated this is bug, since don't recall it being pre-update:
messages in your outbox now show delete button, just like inbox messages
for fear of breaking smth, did not click any delete button - unknown if it's functional

**To Reproduce**
1. enter outbox
2. see delete button on messages, both pre- & post-update

**Expected behavior**
no delete button

**Screenshots**
![Screenshot from 2021-01-25 17-41-20](https://user-images.githubusercontent.com/77951485/105775413-c603ad80-5f34-11eb-894f-5348f5db0a17.png)
^ message sitting in outbox (sent to self yesterday as test)

**Desktop (please complete the following information):**
 - OS: linux mint
 - Browser firefox
 - Version 84.0.2

**Additional context**
in fairness this would be neat as feature, having ability hide messages from outbox since page can get v long - but submitting as bug just cause not sure!!

**Comment by MasterSteelblade** [comment]
Not a bug! This is so that if people want to remove something from their outbox they can, rather than it staying there forever.
