### ISSUE TITLE
[BUG] comment only works from dashboard

### ISSUE THREAD

**Issue by autiestella** [MasterSteelblade/WaterfallBugsFeatures#52]
**Describe the bug**
can't comment on posts unless from the dashboard 

**To Reproduce**
1. go to direct link of post
2. attempt to comment - textbox will pop up & can be filled in, but hitting "comment" after does nothing
3. go to homepage of blog, attempt to comment on post, same as above 
4. go back to dashboard - comment works

**Expected behavior**
to be able to comment regardless where from 

**Desktop (please complete the following information):**
 - OS: linux mint
 - Browser firefox
 - Version 84.0.2

**Comment by MasterSteelblade** [comment]
Possibly fixed - give it a go?

**Comment by autiestella** [comment]
looks like works, both tests gone through!! :D

**Comment by MasterSteelblade** [comment]
Awesome! In that case, marking as fixed!
