### ISSUE TITLE
[BUG] Polls will not post with quotations in selectable options

### ISSUE THREAD

**Issue by JasvinFellOver** [MasterSteelblade/WaterfallBugsFeatures#53]
**Describe the bug**
If you try to create a poll and the poll's option(s) contain multiple words with at least one of them being inside quotations (ex: "word" word) the poll will fail to post

**To Reproduce**
1. Go to create a text post
2. Set up a poll with at least one option containing multiple words with at least one within quotations
3. Click post

**Expected behavior**
The poll is posted

**Screenshots**
![Screenshot 2021-01-26 032328](https://user-images.githubusercontent.com/78017338/105826882-e3f9fe00-5f86-11eb-8b0c-504a21122d2b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 20H2

**Additional context**
Problem might be with quotations as a whole in poll options as I found a second, even less significant, bug while recreating this one for the screenshot. If the poll option(s) only contain a single word in quotations, the poll will still post and the quotation marks just get deleted for whatever reason.

**Comment by MasterSteelblade** [comment]
Fixed - it's a hacky fix, but it is a fix.
