### ISSUE TITLE
[BUG]  Blacklist only blocks one tag

### ISSUE THREAD

**Issue by Ahlberger** [MasterSteelblade/WaterfallBugsFeatures#54]
**Describe the bug**
Blacklist seems to only block one tag at a time (whichever you added most recently). There's also no list where you can see which tags you have already added to blacklist

**To Reproduce**
I had added both #furry and #nsfw. Went on the art discovery page, saw lots of nsfw blocked but no furry blocked. Went back to blacklist, added furry, and went back to art discovery. Now furry was blocked but nsfw was not.

1. Go to User settings-blacklist
2. Add common tag to blacklist
3. Go to art discovery, 
4. See tag blocked
5. Go back to blacklist
6. Add another tag to blacklist
7. Go back to art discovery
8. See error: first tag is no longer blocked

**Expected behavior**
I expect all the tags I added to blacklist to be blocked on my dash/art discovery. I also expect to see a list of which tags I have already blocked, with a way of removing them from blacklist if necessary.

**Smartphone (please complete the following information):**
 - Device: Samsung S7
 - OS: Android 8.0.0
 - Browser: Brave (chromium)
 - Version: Brave 1.19.86 (Chromium 88.0.4324.96)

**Additional context**
Not tested on desktop

**Comment by MasterSteelblade** [comment]
This should now be fixed.
