### ISSUE TITLE
Cannot access Adultmarked blogs as an adult, seemingly can't see what the date of birth they entered is[BUG] 

### ISSUE THREAD

**Issue by Pondohou** [MasterSteelblade/WaterfallBugsFeatures#56]
Cannot access adult marked blogs, even explicit and nsfw posts flipped on, while being an adult and having entered a date of birht to show such.

This is what i did when entering date of birth:

1. log in and get to the new date of birth page

2 . open the small scroll menues to pick my date of birth

3. Select month and year but skip entering the DAY

4. the site accepted that date of birth even without the DAY entered.

I thought maybe i was allowed to enter only putting in month and year, but now i am locked out from adult marked blogs.
I think the date of birth site needs to be edited so it doesnt accept you in unless you enter your full date of birth. 

Windows
Firefox
84.0.2 64-bit

**Additional context**
I also have both explicit and nsfw post buttons flipped on so that shouldnt be affecting this issue.

**Comment by MasterSteelblade** [comment]
Can't find anything in the database that looks like a bad date and I can't get it to accept a date without a day set either, so it's more likely you just entered the date wrong. Closing due to not being able to replicate.
