### ISSUE TITLE
[BUG] Lack of confirmation when sending a private ask

### ISSUE THREAD

**Issue by ICantChooseNames** [MasterSteelblade/WaterfallBugsFeatures#59]
**Describe the bug**
When responding to an ask, you have the option to respond privately. However, doing so just returns an error saying 'There was an error trying to post. Please contact support' and it keeps you on the page, which makes it appear that your response did not send when in reality it did. You can even send multiple of the same response in this way because all the information is still there.

**To Reproduce**
1. Receive an ask
2. Reply to ask with the "Answer Privately" toggle enabled
3. See error
4. If you really want to, press "Post" again to send the exact same ask to the recipient
5. If you complete step 4, look into your outbox and look at what you've just done.

**Expected behavior**
The page to update with confirmation that the user has responded to the ask.

**Screenshots**
![image](https://user-images.githubusercontent.com/77937232/105881917-13365c80-5fd3-11eb-9785-fd6be1b26245.png)
![image](https://user-images.githubusercontent.com/77937232/105881972-21847880-5fd3-11eb-9807-9fc5a980f4ef.png)

**Desktop (please complete the following information):** 
- OS: OpenSUSE Leap 15.2
- Browser: Firefox
- Version 78.6.1esr (64-bit)

**Additional context**
I accidentally sent 3 of essentially the same ask this way because I didn't realise that the original reply sent and so I'm sorry for sending slight inbox spam ;^;

**Comment by leporid5873** [comment]
seeing as #41 (is that now linked or not omg) also has a private ask issue, i think there are a couple bugs?
![Screenshot_20210127-030558_Hermit](https://user-images.githubusercontent.com/77962916/105932298-022a3180-604d-11eb-89d6-c309b3f4eb58.jpg)
![Screenshot_20210127-030313_Hermit](https://user-images.githubusercontent.com/77962916/105932308-035b5e80-604d-11eb-8120-b74d2e3d1de4.jpg)
i unchecked private answer and it "officially" went through ^^

**Comment by MasterSteelblade** [comment]
This Should:tm: be fixed in tonights patch, so closing as fixed.
