### ISSUE TITLE
[BUG] Sneaky footer behind askbox

### ISSUE THREAD

**Issue by Vyling** [MasterSteelblade/WaterfallBugsFeatures#60]
**Describe the bug**
When having the browser window at ~1000px on the askbox page, the footer can be partly seen behind the askbox.

**To Reproduce**
1. Go to any askbox
2. Make the window ~1000px wide
3. Look at the right side of the askbox

**Expected behavior**
The footer should be at the bottom of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/30179258/105903974-ddb86000-6020-11eb-99f3-a33ebed615b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi
 - Version latest

**Additional context**
This actually looks funny.

**Comment by MasterSteelblade** [comment]
A patch will be deployed in a few hours that solves this, once the conversion process finishes. Closing as fixed!
