### ISSUE TITLE
[BUG] Audio posts auto-playing if multiple are on a page

### ISSUE THREAD

**Issue by ICantChooseNames** [MasterSteelblade/WaterfallBugsFeatures#62]
**Describe the bug**
While looking through one of my blog's audio tag to find something, I clicked play on one of the audio players and found that the rest of the audio players started as soon as the one above it stopped.

**To Reproduce**
1. Find a page with multiple audio players (e.g. A blog's audio tag)
2. Play an audio that's above other audio players
3. Hear chain reaction

**Expected behavior**
For no audio to play after the selected audio player has finished playing its file.

**Desktop (please complete the following information):**
- OS: OpenSUSE Leap 15.2
- Browser: Firefox
- Version 78.6.1esr (64-bit)

**Comment by MasterSteelblade** [comment]
_Possible_ fix submitted - can you test?

**Comment by ICantChooseNames** [comment]
Tested- Other audio posts still play after the one I selected

**Comment by MasterSteelblade** [comment]
Interesting... On Firefox 85 it's working fine and only playing one at a time. I'll leave this open for now so if anyone else is having issues they can chime in, but my instinct is that it's because it's an old version of Firefox, even if it is an ESR release.

**Comment by ICantChooseNames** [comment]
Huh... Very odd. If it's working for you I'm not sure what my issue could possibly be... Ah well ^^''

Just tried accessing via up-to-date browsers on Windows 10, (Firefox 85.0 (64-bit) and Chrome Version 88.0.4324.104 (64-bit)) and it still happened- However, it didn't happen for me on mobile (basic browser version 5.2.38C29, Android version 5.0.1). Hopefully if someone else has the issue they'll have more useful info
