### ISSUE TITLE
[BUG] Queue "next" button leads to "liked posts" not next queue page

### ISSUE THREAD

**Issue by Kismuntr** [MasterSteelblade/WaterfallBugsFeatures#64]
**Describe the bug**
When inside your queue and trying to go to the next page it links to the "liked" feed.

**To Reproduce**
1. Go to your queue
2. Click on 'Next' (requires enough queued posts to have a second page I assume)
3. land on "liked submissions page 2" instead of queue page 2

**Expected behavior**
To reach the second page of your queued submissions.

**Screenshots**
![2021-01-27_02h14_22](https://user-images.githubusercontent.com/78037174/105928123-a5774880-6045-11eb-9f50-020da39ed722.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser Firefox
 - Version 84.0.2

**Additional context**
I assume it is just a linking error with the "liked submissions" feed.

**Comment by MasterSteelblade** [comment]
Should be fixed, give it a check?

**Comment by Kismuntr** [comment]
Yes, works now. Thank you!
