### ISSUE TITLE
[BUG] Editing draft post deletes image ID/caption

### ISSUE THREAD

**Issue by MarrowInTheBone** [MasterSteelblade/WaterfallBugsFeatures#65]
**Describe the bug**
If you upload an image and enter an image ID and/or caption, save as a draft and come back to edit said post, the image ID/caption previously entered will be deleted.

**To Reproduce**
1. Upload an image via image post
2. Enter an image ID/caption
3. Save as draft
4. Go to your draft page and select the edit button on said post
4. See image ID/caption as blank

**Expected behavior**
The image ID and caption should be saved.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/77948273/105927955-a3dc5f00-600a-11eb-9532-7773b50e254f.PNG)
![Capture1](https://user-images.githubusercontent.com/77948273/105927961-a8087c80-600a-11eb-8962-35c934ed667c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 84.0.2 (64-bit)

**Additional context**
This also occurred on my Android smartphone using the DuckDuckGo mobile browser.

**Comment by ICantChooseNames** [comment]
this also seems to happen when you post a post with an image that has caption/image ID as well- I had gone to edit a picture's image ID earlier because I thought it could be worded a bit better and I had to re-enter it into the text box

**Comment by MasterSteelblade** [comment]
Possibly fixed - give it a go?

**Comment by ICantChooseNames** [comment]
I know I'm not OP but it's working for me now ^^ (Both editing a draft and editing a posted image)

**Comment by MarrowInTheBone** [comment]
I just checked and it is also working for me. Thank you!
