### ISSUE TITLE
[BUG] Random \ appearing in tags when * are used around a word in tags

### ISSUE THREAD

**Issue by LapisPancake** [MasterSteelblade/WaterfallBugsFeatures#67]
**Describe the bug**
When using * around text in the tags, the finished post shows random \ besides the * as well.

Edit to add; I had to take my typed examples out because turns out, text formatting is a thing here. sob

**To Reproduce**
1. Go to make a new post. Note; For me it happened in a normal text post. I haven't tested other post types.
2. Write something in the tags, and have a word surrounded by *.
3. Post.
4. The finished post will now have put \ beside the * around the word.

**Expected behavior**
The \ to not appear.

**Screenshots**
![hkdjgfhkjgfdkhj](https://user-images.githubusercontent.com/78064132/105947658-c8b3ef00-6069-11eb-8656-2f07f751b3b6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 84.0.2 (64-Bit)

**Smartphone (please complete the following information):**
Did not test on smartphone since I use WF on desktop only.

**Additional context**
It does help emphasizing words though, all things considered.
Sorry, that's not funny.

**Comment by MasterSteelblade** [comment]
Fixed for new tags - old ones can be edited, but can't be retroactively fixed.
