### ISSUE TITLE
[BUG] User Settings can't be saved/not automatically saved

### ISSUE THREAD

**Issue by TheBaddest** [MasterSteelblade/WaterfallBugsFeatures#68]
**Describe the bug**
User Settings not automatically saved / No Save Settings button 

Log in
Click on User Settings/Blog Settings
Change some settings
look for "save settings" button, not found
try to add some blacklisted tags, CSRF Error
refresh page, settings not changed

**Expected behavior**
Settings changed by users are automatically saved/have a "save settings" button, settings persist after refreshing the page.

Desktop PC
 - OS: Windows 10 19041.746
 - Browser: Chrome  87.0.4280.141

**Comment by ICantChooseNames** [comment]
It's very confusing, but there is a button to submit changes... It just happens to look like it only applies to blacklist tags. Issue #17 suggests a change to this so it's more obvious
![image](https://user-images.githubusercontent.com/77937232/106014146-33c1ed80-608b-11eb-9212-0a4bcd0182b7.png)
I think this page may also be affected by the thing where if you press enter in a text box, that _also_ submits changes? I didn't test yet ^^''

**Comment by el-o-l** [comment]
> It's very confusing, but there is a button to submit changes... It just happens to look like it only applies to blacklist tags. Issue #17 suggests a change to this so it's more obvious
> ![image](https://user-images.githubusercontent.com/77937232/106014146-33c1ed80-608b-11eb-9212-0a4bcd0182b7.png)
> I think this page may also be affected by the thing where if you press enter in a text box, that _also_ submits changes? I didn't test yet ^^''

Despite clicking the submit button under the blacklist tags, I've received an error trying that on desktop whilst trying to switch back to the accessibility font (which I successfully turned on and off in mobile) so I think there's still an issue with saving user settings despite using the button

**Comment by ICantChooseNames** [comment]
> Despite clicking the submit button under the blacklist tags, I've received an error trying that on desktop whilst trying to switch back to the accessibility font (which I successfully turned on and off in mobile) so I think there's still an issue with saving user settings despite using the button

Huh, so it does. Made a new issue page because it seems pretty serious, hope you don't mind

**Comment by MasterSteelblade** [comment]
The CSRF component is fixed and the missing of the save button is a duplicate of #17 so I'll close this for now.
