### ISSUE TITLE
[BUG] Long links cause post widths to widen

### ISSUE THREAD

**Issue by peanutbuttercookiess** [MasterSteelblade/WaterfallBugsFeatures#70]
**Describe the bug**
When using the link post type, entering a long link will cause posts on the dashboard to expand. This effect will spread to any page the link is present on, including your blog, your dashboard, blogs that reblogged the link, and other people's dashboards.

**To Reproduce**
1. Use the Link post type
2. Enter a lengthy link into the "Site URL" box. Links that are too long will push the "Post add-ons" box into the center of the page.
3. Submit post

**Expected behavior**
Link posts with long links will not expand post size.

**Screenshots**
good link size
![postlinkgood](https://user-images.githubusercontent.com/16735794/106041690-1fd9b400-60aa-11eb-876a-1ba68a44ad41.png)
bad link size
![postlinkcentering](https://user-images.githubusercontent.com/16735794/106041598-ff115e80-60a9-11eb-80b8-19a54924d5f6.png)
expanded blog
![expandedblog](https://user-images.githubusercontent.com/16735794/106041607-0173b880-60aa-11eb-9524-0cb5550c7d19.png)
expanded dash
![expanded dash](https://user-images.githubusercontent.com/16735794/106041613-046ea900-60aa-11eb-901a-a1de6c8bd340.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.141

**Additional context**
on the dashboard, the "featured art" box gets pushed to the bottom of the page

**Comment by MasterSteelblade** [comment]
Fixed!
