### ISSUE TITLE
[FEATURE REQUEST] (bugture) tags and #, not urgent

### ISSUE THREAD

**Issue by leporid5873** [MasterSteelblade/WaterfallBugsFeatures#72]
**Motivation and Context**
I'm lazy. That's it.

**Is your feature request related to a problem? Please describe.**
I mean I guess the feature is already implemented, if I copy a list of tags from my first post to paste them into a reblog: It translates the # into commas.
![Screenshot_20210128-022621_Hermit](https://user-images.githubusercontent.com/77962916/106076889-c8226380-6110-11eb-9d5a-f5e8241ca8c3.jpg)
Except the first #, which leads to the first tag startig with ##.

**Describe the feature/solution you'd like**
That all # from the pasted text disappear ^^

**Describe alternatives you've considered**
I think you can ctrl+F the # 's on pc? Not on a mobile device. Which will get an app. So, not urgent at all. Also I can just go edit lol I was just too lazy to delete all # 's or edit the older post and cooy from there.

**Comment by MasterSteelblade** [comment]
Fixed in tonights patch
