### ISSUE TITLE
[FEATURE REQUEST] override to view own DNR/DNI posts

### ISSUE THREAD

**Issue by autiestella** [MasterSteelblade/WaterfallBugsFeatures#73]
**Motivation and Context**
this was originaly post as comment on #38 (closed bug report) so apology if already been consider, but thought maybe should expand here & see also if others got thoughts!!

**Is your feature request related to a problem? Please describe.**
after updates disallowing viewing of any DNR/DNI posts in tags, some tag pages on blogs become (near)-empty & can't easily reference back
this is welcome change viewing others' blogs, knowing much harder stumble on stuff like vents... but this even applies to yourown blog! if got sketches/wips tagged DNR in an art tag, an index post for character info tagged DNR, old text posts tagged DNR to prevent spread of posible misinfo/personal ref/etc, you no longer can easily find these since they don't show up - even when not trying to look at DNR/DNI tags themselves, these posts render invisible. even frequently-use tags can look barren
ofcourse posts still exist, it's just lot harder to find 

**Describe the feature/solution you'd like**
a built-in override to allow viewing of DNR/DNI tagged posts, **only** for your own blog/tag pages 

**Describe alternatives you've considered**
not sure what could be  alternative

**Is there a way to do this already?**
1. save direct links to each post you tag dnr/dni, or at least any you want to be able find/edit/delete later
2. dig through entire blog to find specific post
both which kindof defeat purpose of organise stuff in tags, if will not be able easy find later anyway 

**Additional context**
this is issue personaly cause use dnr tags for stuff like dream rambles which not put in files yet, infodumps where trying avoid spread posible misinfo or unconfirm theorys, & random daily rambles where not rly trying start big convo, but just say whatever on mind
also very sorry if wording too unclear! trying best but head hurting, please let know if might need try reword

**Comment by MasterSteelblade** [comment]
This is out of scope for the DNR/DNI system - they're not intended to be used as an archive. It's provided as a convenience for one-off posts, but the assumption is 99.9%+ of a user's content will be public and shareable, and I'm not adding systems to make that not the case since there are better platforms for this kind of thing.
