### ISSUE TITLE
[BUG] Follow Button Missing

### ISSUE THREAD

**Issue by defsiarte** [MasterSteelblade/WaterfallBugsFeatures#76]
**Describe the bug**
When looking at users' profiles, the follow button is missing from the header. 

**To Reproduce**
1. Go to user profile
2. Look at top of screen
3. There's no follow button

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 85
<img width="956" alt="wf_support_2" src="https://user-images.githubusercontent.com/39251294/106311359-04e67b80-6233-11eb-852c-dc478b5e3da6.png">

**Additional context**

**Comment by Vyling** [comment]
It's weird... I can see the follow button on that profile.

**Comment by MasterSteelblade** [comment]
I've not been able to reproduce this and there haven't been any other reports, so it's possible this was accidentally fixed in an incidental update. Marking as closed unless anyone else has it.
