### ISSUE TITLE
[BUG] Menu not working on mobile.

### ISSUE THREAD

**Issue by theatricalis** [MasterSteelblade/WaterfallBugsFeatures#77]
**Describe the bug**
When selecting the menu on a mobile browser, the menu will appear behind the posts on my dashboard, and nothing from the menu can be selected. 

**Screenshots**
![C331BF0C-3B1E-4E42-8928-84C93DCB2FF1](https://user-images.githubusercontent.com/78232065/106319339-e7b3ac00-6236-11eb-95be-ebcb9f9d2da6.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: iOS 14.3
 - Browser: Safari

**Additional context**
Note: I downloaded app versions of both Firefox and Chrome to my iPhone as well, and had the same problem between all three browsers. I suspect it’s either a site issue or an issue with my phone. Either way, I hope this helps!

**Comment by MasterSteelblade** [comment]
This issue seems specific to iOS, I'm not entirely sure why yet. Confirmed as multiple people have reported it.

**Comment by MasterSteelblade** [comment]
Unfortunately, this doesn't seem fixable currently without completely starting the UI from scratch, so going to have to close this for now. I'll add it to the list of things to test in the new UI, but the only Apple device I have can't run anything newer than iOS 12, so if this was introduced after that it'll likely persist.
