### ISSUE TITLE
[BUG] Can't Retitle Art Post

### ISSUE THREAD

**Issue by JayZX535** [MasterSteelblade/WaterfallBugsFeatures#82]
**Describe the bug**
Accidentally entered the incorrect name for an art post and am now unable to retitle it.  Changing the name in the editing menu and hitting submit does nothing, the name reverts when redirected back.

**To Reproduce**
1. Create an art post
2. Edit the art post
3. Change the text in the title of the post
4. Hit submit
5. Check name of post for updates.

**Expected behavior**
Submitted text changes should correctly update when the edit is submitted.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Firefox
 - Version 85.0

**Comment by MasterSteelblade** [comment]
Should now be fixed. Sorry for the wait!
