### ISSUE TITLE
[BUG] Can't unpin posts

### ISSUE THREAD

**Issue by MarrowInTheBone** [MasterSteelblade/WaterfallBugsFeatures#83]
**Describe the bug**
If you pin a post and then try to unpin it, the post remains pinned. When trying to go back to the post you editted to unpin, the toggle is still set to on.

**To Reproduce**
1. Make a post
2. Edit said post and toggle on 'Pin this post' then save the post
3. Edit said post again and unpin the post
3. Go to your blog

**Expected behavior**
Editing a post to no longer be pinned should save that setting.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 85.0 (64-bit)

**Additional context**
The only way to get a post unpinned is to delete it.

**Comment by MasterSteelblade** [comment]
Fixed! Sorry for the delay.
