### ISSUE TITLE
[BUG] Can't edit tags on repours of art/image posts

### ISSUE THREAD

**Issue by greysdawn** [MasterSteelblade/WaterfallBugsFeatures#85]
**Describe the bug**
Editing tags on repours (reblogs) of art/image posts fails with an error stating to contact support.

**To Reproduce**
1. Create an art or image post
2. Attempt to repour it, either through quick reblog or through regular means. Be sure to add at least one tag
3. Edit the repour to change the text of a tag
4. Attempt to save
5. Observe error

**Expected behavior**
The edit should succeed and be posted.

**Screenshots**
![before edit](https://user-images.githubusercontent.com/29555267/106619153-45e5d500-653e-11eb-9a70-8a04fec8d194.png)
![after edit](https://user-images.githubusercontent.com/29555267/106619242-5eee8600-653e-11eb-9d92-55adf1d13d0a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.104 (latest)

**Additional context**
This bug doesn't seem to be an issue with text-based posts, though I only tried it with text, link, image, and art posts altogether.

**Comment by MasterSteelblade** [comment]
Tried this a few times and can't replicate it.
