### ISSUE TITLE
[BUG] Pressing enter to submit quick repours produces error

### ISSUE THREAD

**Issue by greysdawn** [MasterSteelblade/WaterfallBugsFeatures#86]
**Describe the bug**
Pressing the enter key to submit a quick repour from the `tags` field results in a page reading `{"code": "ERR_INVALID"}`.

**To Reproduce**
1. Attempt a quick repour on a post
2. Navigate to the tag field, then press enter
3. Observe the error page

**Expected behavior**
The repour should be submitted successfully, or the input (enter key) should be ignored/discarded

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.104 (latest)

**Comment by MasterSteelblade** [comment]
Should be fixed now.
