### ISSUE TITLE
Can't toggle access to adult only blogs

### ISSUE THREAD

**Issue by Deviruchan** [MasterSteelblade/WaterfallBugsFeatures#88]
**Describe the bug**
I can't seem to toggle on adult only blogs despite being 18+. I can still see and toggle NSFW post but not blogs. I can't even view my own blogs.
![Locked frrom own blog](https://user-images.githubusercontent.com/43758248/107076565-99178c00-67b9-11eb-94cd-791091cfba25.png)

![No adult only toggle](https://user-images.githubusercontent.com/43758248/107076378-5c4b9500-67b9-11eb-89a7-aae296e50637.png)

**Comment by MasterSteelblade** [comment]
Hi - if you can contact support with your email and proper birthday, this can be fixed, there was an oversight in the account update code that sometimes didn't put a real date in. Sorry!
