### ISSUE TITLE
[BUG] Readmore in reblogs not working

### ISSUE THREAD

**Issue by 80Roxy08** [MasterSteelblade/WaterfallBugsFeatures#96]
**Describe the bug**
When putting a readmore in a text post that is a reblog of another, the readmore does not works, instead putting a string of text.

**To Reproduce**
1. Go to "Reblog"
2. Add a readmore in the reply of the reblog
3. Add test under the readmore
4. Hit post, see the error

**Expected behavior**
The reblogged post also has a working readmore under the first post's readmore.

[Link to example post.](https://80roxy08.waterfall.social/post/477540)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox 
 - Version: 86.0 (64 bits)

**Comment by MasterSteelblade** [comment]
Fixed!
